/**
 * MidePay — Vercel Build Script
 * 
 * Safely generates config.js at build time using Vercel Environment Variables:
 * - SUPABASE_URL
 * - SUPABASE_ANON_KEY
 */

const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';

const configContent = `/**
 * MidePay — Runtime Configuration
 * Automatically generated by Vercel build step from environment variables.
 */

window.MIDEPAY_SUPABASE_CONFIG = {
  url: ${JSON.stringify(supabaseUrl)},
  anonKey: ${JSON.stringify(supabaseAnonKey)}
};
`;

const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ [Vercel Build] config.js generated successfully.');
if (supabaseUrl && supabaseAnonKey) {
  console.log(`⚡ Connected to Supabase: ${supabaseUrl}`);
} else {
  console.warn('⚠️ [Vercel Build] SUPABASE_URL or SUPABASE_ANON_KEY not set in Environment Variables. Running in simulation mode.');
}
