/**
 * MidePay — Vercel Build Script
 * 
 * Safely generates config.js at build time using Vercel Environment Variables:
 * - SUPABASE_URL
 * - SUPABASE_ANON_KEY
 */

const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, 'config.js');
let existingUrl = '';
let existingAnonKey = '';

try {
  if (fs.existsSync(configPath)) {
    const existing = fs.readFileSync(configPath, 'utf8');
    const urlMatch = existing.match(/url:\s*['"]([^'"]+)['"]/);
    const keyMatch = existing.match(/anonKey:\s*['"]([^'"]+)['"]/);
    if (urlMatch && urlMatch[1]) existingUrl = urlMatch[1];
    if (keyMatch && keyMatch[1]) existingAnonKey = keyMatch[1];
  }
} catch (e) {}

const supabaseUrl = process.env.SUPABASE_URL || existingUrl || 'https://pxdzdehocjnmxbuvipxu.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || existingAnonKey || 'sb_publishable_5adXF0UhSQJ1n4F_IqLXEw_0naxL0wT';

const configContent = `/**
 * MidePay — Runtime Configuration
 * Automatically generated by Vercel build step from environment variables.
 */

window.MIDEPAY_SUPABASE_CONFIG = {
  url: ${JSON.stringify(supabaseUrl)},
  anonKey: ${JSON.stringify(supabaseAnonKey)}
};
`;

fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ [Vercel Build] config.js generated successfully.');
if (supabaseUrl && supabaseAnonKey) {
  console.log(`⚡ Connected to Supabase: ${supabaseUrl}`);
} else {
  console.warn('⚠️ [Vercel Build] SUPABASE_URL or SUPABASE_ANON_KEY not set in Environment Variables. Running in simulation mode.');
}
